# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cart_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.TextField(default=None, null=True),
        ),
    ]
