# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
