# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 05:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cart_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last4', models.IntegerField()),
                ('expiry', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_cards',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='varient',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
